_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.0
            "8":
                - 5
            "12": 0.18.0
            "13": darwin-arm64
architecture:
    value: LSTM
dataset:
    value: tracking_data_full_subset2
epochs:
    value: 10
hidden_size:
    value: 128
input_size:
    value: 62
learning_rate:
    value: 0.001
num_layers:
    value: 2
output_size:
    value: 62
